//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Environment
{
	public virtual int numNPC
	{
		get;
		set;
	}

	public virtual int numMoney
	{
		get;
		set;
	}

	public virtual int numWeapon
	{
		get;
		set;
	}

	public virtual IEnumerable<Street> Street
	{
		get;
		set;
	}

	public Environment()
	{
	}

}

