//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Mission
{
	public virtual IEnumerable<Environment> Environment
	{
		get;
		set;
	}

	public virtual void selectMission()
	{
		throw new System.NotImplementedException();
	}

	public Mission()
	{
	}

	public virtual void Mission_1()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Mission_2()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Mission_3()
	{
		throw new System.NotImplementedException();
	}

}

