//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NPC : Character
{
	public virtual bool isHostile
	{
		get;
		set;
	}

	public NPC()
	{
	}


	public override void addWeapon()
	{
		throw new NotImplementedException();
	}

	public override void useWeapon()
	{
		throw new NotImplementedException();
	}

	public override void showInventory()
	{
		throw new NotImplementedException();
	}
}

