//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Street : Environment
{
	public virtual object numHouses
	{
		get;
		set;
	}

	public virtual IEnumerable<House> House
	{
		get;
		set;
	}

	public Street()
	{
	}

}

