//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tool : Item
{
	public virtual int repairSkill
	{
		get;
		set;
	}

	public virtual int breachSkill
	{
		get;
		set;
	}

	public Tool()
	{
	}

}

