//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Weapon
{
	public virtual int damage
	{
		get;
		set;
	}

	public virtual int condition
	{
		get;
		set;
	}

	public virtual int skill
	{
		get;
		set;
	}

	public virtual Humanoid Humanoid
	{
		get;
		set;
	}

}

