//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Humanoid
{
    public virtual string name { get; set; }
	public virtual int strength	{ get; set;	}
	public virtual int weaponSkill { get; set; }
	public virtual int attack {	get; set; }
	public virtual int speed { get; set; }
	public virtual int health { get; set; }
	public virtual int level { get; set; }
    public List<Weapon> weaponList = new List<Weapon>();

	public Humanoid() { }
	public Humanoid(string name, int streangth, int weaponSkill, int attack, int speed, int health, int level)
	{
        this.name = name;  this.strength = strength; this.weaponSkill = weaponSkill; this.attack = attack; this.health = health; this.level = level;
	}

    public abstract void addWeapon(Weapon w);
    public abstract void useWeapon(Weapon w);
    public abstract void showInventory();
}

